Добавил в пакет TypeHandler
Byndyusoft/Byndyusoft.Data.Relational pull request #21
Opened 2023-06-19 05:20 UTC by Alex-Grigorichev

Добавил в пакет логику по добавлению JsonTypeHandler, покрыл тестами.
Поднял версию пакета до релизной (0.10.0)

2023-06-19 06:18 UTC, govorovvs requested changes

2023-06-19 06:18 UTC, govorovvs commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
может сделать DefaultJsonTypeHandlerOptions самостоятельным публичным классом?

2023-06-19 06:33 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Не совсем понимаю зачем. Так как не вижу способов применения этого класса во вне.

2023-06-19 09:22 UTC, govorovvs commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Если у тебя много типов, которые ты хочешь сохранять через JsonTypeHandler, то  было бы удобно где-то в одном месте задать дефолтные настройки

2023-06-19 10:58 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Добавил возможность задать другие дефолтные настройки

2023-06-19 11:00 UTC, Alex-Grigorichev commented on Directory.Build.props
> +		<Version>0.10.0</Version>
Я не уверен, что выбрал правильную версию, по каким правилам мы считаем когда у нас rc, а когда уже релизная версия, которую можно отдавать наружу?

2023-06-19 11:46 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Сократил название

2023-06-20 10:32 UTC, govorovvs commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
можем сделаем `JsonTypeHandler.DefaultSerializerOptions`?

2023-06-20 10:57 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Да, вынес JsonSerializerOptions в класс JsonTypeHandler, также сделал гетер приватным

2023-06-20 11:11 UTC, govorovvs commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
т.е. использование будет таким?
```
JsonTypeHandler<User>.DefaultSerializerOptions
```

2023-06-20 11:16 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
да

2023-06-20 11:38 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
выглядит не очень, но особо не могу придумать как это сделать лучше

2023-06-20 12:19 UTC, govorovvs commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
но ты же понимаешь, что 
```
JsonTypeHandler<User>.DefaultSerializerOptions
```
и 
```
JsonTypeHandler<Document>.DefaultSerializerOptions
```
это разные экземпляры

2023-06-20 12:29 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Да, теперь понимаю, никогда раньше не сталкивался со статическими свойствами внутри классов с дженерик параметрами
Как в таком случае должно выглядеть JsonTypeHandler.DefaultSerializerOptions?

2023-06-20 18:28 UTC, govorovvs commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
JsonTypeHandler.DefaultSerializerOptions - да

2023-06-21 04:35 UTC, Alex-Grigorichev commented on src/Byndyusoft.Data.Relational/TypeHandlers/JsonTypeHandler.cs
> +    internal static class DefaultJsonTypeHandlerOptions
Перенёс

2023-06-22 08:43 UTC, govorovvs approved these changes, later dismissed

2023-06-22 09:39 UTC, Rinatich commented on tests/Functional/JsonTypeHandlerTests.cs
> +    class Row
Есть неочевидно поведение, если в User будет лежать 'null' (если кто-то сохранил вручную в БД)
Может, явно тест-кейс создать, чтобы было видно, что в текущей реализации это так.
Что думаешь?

2023-06-23 04:07 UTC, Alex-Grigorichev commented on tests/Functional/JsonTypeHandlerTests.cs
> +    class Row
Добавил тест-кейс, добавил в ридми

2023-06-26 05:39 UTC, Rinatich requested changes

2023-06-26 05:39 UTC, Rinatich commented on Directory.Build.props
> +		<Version>0.10.0-rc4</Version>
а почему rc?)

2023-06-26 06:27 UTC, Alex-Grigorichev commented on Directory.Build.props
> +		<Version>0.10.0-rc4</Version>
не был уверен, что нужно делать релиз, так как до этого было rc3, обсудили с Витей, удаляю rc делаю релизную версию

2023-06-26 06:36 UTC, Rinatich requested changes

2023-06-26 06:36 UTC, Rinatich commented on Directory.Build.props
> +		<Version>0.10.0</Version>
а не надо версию поднимать? Ты добавил фичу, нужно поднять минорную версию

2023-06-26 06:46 UTC, Alex-Grigorichev commented on Directory.Build.props
> +		<Version>0.10.0</Version>
поднял

2023-06-26 07:14 UTC, Rinatich approved these changes

2023-06-27 07:41 UTC, merged